window.WATCHES.push({
  brand: "Lip",
  id: "lip-himalaya",
  name: "Himalaya",
  year: 1954,
  img: "https://via.placeholder.com/300",
  description: "Un modèle historique.",
  specs: [
    { label: "Boîtier", value: "Acier 38 mm" }
  ]
},
                   {
  brand: "Lip",
  id: "lip-calendrier",
  name: "Calendrier",
  year: 1946,
  img: "https://via.placeholder.com/300",
  description: "Un modèle historique et reconnaissable par sa forme atypique et simpliste.",
  specs: [
    { label: "Boîtier", value: "Acier 38 mm" }
  ]
},
                     {
  brand: "Lip",
  id: "lip-test",
  name: "Test",
  year: 2015,
  img: "https://via.placeholder.com/300",
  description: "Un simple test.",
  specs: [
    { label: "TESTS", value: "Acier 70 mm" }
  ]
},
                            {
  brand: "Lip",
  id: "lip-incabloc",
  name: "Incabloc",
  year: 1963,
  img: "https://via.placeholder.com/300",
  description: "La simplisité sur un poignet",
  specs: [
    { label: "Boîtier", value: "Acier 40 mm" }
  ]
},
{brand:"Lip",id:"lip-churchill-671939-2025",name:"Churchill 671939",year:2025,img:"liens-photos/lip-pic/churchill_671939_2025.avif",description:"Montre rectangulaire élégante de la collection Churchill, au design Art Déco emblématique.",specs:[{label:"Boîtier",value:"Acier rectangulaire 28 mm"},{label:"Mouvement",value:"Quartz"},{label:"Étanchéité",value:"30 m"},{label:"Verre",value:"Minéral"}],history:`Modèle 2025 de la gamme Churchill, reprenant les codes historiques de Lip avec un style raffiné et intemporel.`,price:"200 €",notes:`Infos issues du catalogue Lip 2025.`,bibliography:[{label:"Site officiel Lip",url:"https://www.lip.fr"}]},
{brand:"Lip",id:"lip-churchill-671938-2025",name:"Churchill 671938",year:2025,img:"liens-photos/lip-pic/churchill_671938_2025.avif",description:"Version raffinée de la Churchill avec cadran travaillé et silhouette rectangulaire classique.",specs:[{label:"Boîtier",value:"Acier rectangulaire 28 mm"},{label:"Mouvement",value:"Quartz"},{label:"Étanchéité",value:"30 m"},{label:"Verre",value:"Minéral"}],history:`Une déclinaison 2025 de la Churchill, fidèle à l’esthétique Art Déco qui a fait la renommée de Lip.`,price:"200 €",notes:`Infos issues du catalogue Lip 2025.`,bibliography:[{label:"Site officiel Lip",url:"https://www.lip.fr"}]},
{brand:"Lip",id:"lip-churchill-671937-2025",name:"Churchill 671937",year:2025,img:"liens-photos/lip-pic/churchill_671937_2025.avif",description:"Une version élégante de la Churchill avec un cadran épuré et un boîtier rectangulaire signature.",specs:[{label:"Boîtier",value:"Acier rectangulaire 28 mm"},{label:"Mouvement",value:"Quartz"},{label:"Étanchéité",value:"30 m"},{label:"Verre",value:"Minéral"}],history:`Modèle 2025 reprenant l’esprit historique de la Churchill, symbole du style Lip depuis des décennies.`,price:"200 €",notes:`Infos issues du catalogue Lip 2025.`,bibliography:[{label:"Site officiel Lip",url:"https://www.lip.fr"}]},
{brand:"Lip",id:"lip-churchill-c18-2025",name:"Churchill C18",year:2025,img:"liens-photos/lip-pic/churchill_c18_2025.avif",description:"Version mécanique de la Churchill, au style Art Déco affirmé et au charme traditionnel.",specs:[{label:"Boîtier",value:"Acier rectangulaire 32 mm"},{label:"Mouvement",value:"Mécanique à remontage manuel"},{label:"Étanchéité",value:"30 m"},{label:"Verre",value:"Minéral bombé"}],history:`La Churchill C18 perpétue la tradition des montres mécaniques Lip, avec un design inspiré des années 30.`,price:"250 €",notes:`Infos issues du catalogue Lip 2025.`,bibliography:[{label:"Site officiel Lip",url:"https://www.lip.fr"}]},
{brand:"Lip",id:"lip-churchill-t24-2025",name:"Churchill T24",year:2025,img:"liens-photos/lip-pic/churchill_t24_2025.avif",description:"Version automatique de la Churchill, combinant élégance Art Déco et mouvement moderne.",specs:[{label:"Boîtier",value:"Acier rectangulaire 32 mm"},{label:"Mouvement",value:"Automatique"},{label:"Étanchéité",value:"30 m"},{label:"Verre",value:"Minéral bombé"}],history:`La Churchill T24 modernise la ligne historique avec un mouvement automatique tout en conservant son esthétique emblématique.`,price:"300 €",notes:`Infos issues du catalogue Lip 2025.`,bibliography:[{label:"Site officiel Lip",url:"https://www.lip.fr"}]},
{brand:"Lip",id:"lip-general-de-gaulle-671878-2025",name:"Général de Gaulle 671878",year:2025,img:"liens-photos/lip-pic/general_de_gaulle_671878_2025.avif",description:"Montre historique inspirée du modèle porté par le Général de Gaulle, au style sobre et élégant.",specs:[{label:"Boîtier",value:"Acier 38 mm"},{label:"Mouvement",value:"Quartz"},{label:"Étanchéité",value:"50 m"},{label:"Verre",value:"Minéral bombé"}],history:`Version 2025 du modèle emblématique de Lip, reprenant le design porté par le Général de Gaulle dans les années 40. Une pièce historique et intemporelle.`,price:"200 €",notes:`Infos issues du catalogue Lip 2025.`,bibliography:[{label:"Site officiel Lip",url:"https://www.lip.fr"}]},
{brand:"Lip",id:"lip-general-de-gaulle-automatique-35mm-2025",name:"Général de Gaulle Automatique 35 mm",year:2025,img:"liens-photos/lip-pic/general_de_gaulle_auto_35mm_2025.avif",description:"Version automatique du modèle Général de Gaulle, dans un boîtier compact de 35 mm.",specs:[{label:"Boîtier",value:"Acier 35 mm"},{label:"Mouvement",value:"Automatique"},{label:"Étanchéité",value:"50 m"},{label:"Verre",value:"Minéral bombé"}],history:`Interprétation 2025 du modèle historique, équipée cette fois d’un mouvement automatique tout en conservant l’esthétique d’origine.`,price:"350 €",notes:`Infos issues du catalogue Lip 2025.`,bibliography:[{label:"Site officiel Lip",url:"https://www.lip.fr"}]},
{brand:"Lip",id:"lip-type-14-2025",name:"Type 14",year:2025,img:"liens-photos/lip-pic/type_14_2025.avif",description:"Montre inspirée du design historique Lip Type 14, au style épuré et élégant.",specs:[{label:"Boîtier",value:"Acier 38 mm"},{label:"Mouvement",value:"Quartz"},{label:"Étanchéité",value:"50 m"},{label:"Verre",value:"Minéral"}],history:`Réédition 2025 du modèle Type 14, symbole du design français minimaliste des années 50. Une montre simple, fiable et intemporelle.`,price:"180 €",notes:`Infos issues du catalogue Lip 2025.`,bibliography:[{label:"Site officiel Lip",url:"https://www.lip.fr"}]},
{brand:"Lip",id:"lip-nautic-2025",name:"Nautic",year:2025,img:"liens-photos/lip-pic/nautic_2025.avif",description:"Montre sportive inspirée de la Lip Nautic historique, connue pour son style plongeur rétro.",specs:[{label:"Boîtier",value:"Acier 39 mm"},{label:"Mouvement",value:"Automatique"},{label:"Étanchéité",value:"200 m"},{label:"Verre",value:"Saphir"}],history:`La Nautic 2025 modernise la célèbre plongeuse Lip des années 60, avec un design vintage et des performances contemporaines.`,price:"450 €",notes:`Infos issues du catalogue Lip 2025.`,bibliography:[{label:"Site officiel Lip",url:"https://www.lip.fr"}]},
{brand:"Lip",id:"lip-annapurna-2025",name:"Annapurna",year:2025,img:"liens-photos/lip-pic/annapurna_2025.avif",description:"Montre robuste inspirée des modèles d’expédition, pensée pour l’aventure et l’outdoor.",specs:[{label:"Boîtier",value:"Acier 40 mm"},{label:"Mouvement",value:"Quartz"},{label:"Étanchéité",value:"100 m"},{label:"Verre",value:"Saphir"}],history:`La Lip Annapurna 2025 rend hommage aux montres d’exploration de la marque, avec un design utilitaire et une construction résistante.`,price:"250 €",notes:`Infos issues du catalogue Lip 2025.`,bibliography:[{label:"Site officiel Lip",url:"https://www.lip.fr"}]},
{brand:"Lip",id:"lip-nautic-3-quartz-200m-39mm-2025",name:"Nautic 3 Quartz 200M 39 mm",year:2025,img:"liens-photos/lip-pic/nautic_3_quartz_200m_39mm_2025.avif",description:"Réinterprétation moderne de la célèbre plongeuse de 1965, alliant robustesse et précision quartz.",specs:[{label:"Mouvement",value:"Quartz Ronda 515"},{label:"Boîtier",value:"Acier 316L"},{label:"Diamètre",value:"39 mm"},{label:"Étanchéité",value:"200M"}],history:"La lignée Nautic accompagne les plongeurs depuis les années 60, popularisée par Éric Tabarly.",price:"249 €",notes:"Lunette rotative interne bidirectionnelle.",bibliography:[{label:"Site Officiel Lip",url:"https://www.lip.fr"}]},
{brand:"Lip",id:"lip-nautic-w-quartz-200m-39mm-2025",name:"Nautic W Quartz 200M 39 mm",year:2025,img:"liens-photos/lip-pic/nautic_w_quartz_200m_39mm_2025.avif",description:"Variante technique de la Nautic, optimisée pour une lisibilité maximale en milieu aquatique.",specs:[{label:"Mouvement",value:"Quartz"},{label:"Verre",value:"Saphir"},{label:"Index",value:"Luminova"},{label:"Étanchéité",value:"200M"}],history:"Évolution de la gamme Nautic axée sur le design fonctionnel 'W'.",price:"249 €",notes:"Bracelet caoutchouc ou acier selon version.",bibliography:[{label:"Catalogue Lip 2025",url:"https://www.lip.fr"}]},
{brand:"Lip",id:"lip-nautic-w-edition-limitee-exclu-web-2025",name:"Nautic W Édition Limitée (Exclu Web)",year:2025,img:"liens-photos/lip-pic/nautic_w_edition_limitee_exclu_web_2025.avif",description:"Série exclusive numérotée, disponible uniquement en ligne, avec finitions spécifiques.",specs:[{label:"Série",value:"Limitée"},{label:"Mouvement",value:"Quartz"},{label:"Boîtier",value:"Acier sablé"},{label:"Étanchéité",value:"200M"}],history:"Nouvelle stratégie de Lip visant à proposer des modèles exclusifs à sa communauté numérique.",price:"279 €",notes:"Livré dans un coffret spécial.",bibliography:[{label:"Lip Exclusivités",url:"https://www.lip.fr/exclusivites"}]},
{brand:"Lip",id:"lip-himalaya-automatique-coeur-battant-29mm-2025",name:"Himalaya Automatique Cœur Battant 29 mm",year:2025,img:"liens-photos/lip-pic/himalaya_automatique_coeur_battant_29mm_2025.avif",description:"Modèle féminin élégant laissant apparaître l'échappement du mouvement à 12h.",specs:[{label:"Mouvement",value:"Automatique Seiko NH38"},{label:"Diamètre",value:"29 mm"},{label:"Réserve de marche",value:"41h"},{label:"Fond",value:"Transparent"}],history:"L'Himalaya est née d'un défi entre Fred Lip et Maurice Herzog en 1954.",price:"399 €",notes:"Le 'Cœur Battant' est une signature visuelle forte de la gamme.",bibliography:[{label:"Histoire Himalaya",url:"https://www.lip.fr/histoire"}]},
{brand:"Lip",id:"lip-himalaya-classique-29mm-v1-2025",name:"Himalaya Classique 29 mm (Variante 1)",year:2025,img:"liens-photos/lip-pic/himalaya_classique_29mm_v1_2025.avif",description:"L'essence de la montre de ville Lip, format contenu et cadran épuré.",specs:[{label:"Mouvement",value:"Quartz"},{label:"Boîtier",value:"Acier poli"},{label:"Cadran",value:"Argenté"},{label:"Bracelet",value:"Cuir"}],history:"Portée par les plus grands alpinistes français lors des expéditions mythiques.",price:"189 €",notes:"Idéale pour les petits poignets.",bibliography:[{label:"Lip Classic",url:"https://www.lip.fr"}]},
{brand:"Lip",id:"lip-himalaya-classique-29mm-v2-2025",name:"Himalaya Classique 29 mm (Variante 2)",year:2025,img:"liens-photos/lip-pic/himalaya_classique_29mm_v2_2025.avif",description:"Version dorée rose de l'Himalaya 29 mm pour un look plus sophistiqué.",specs:[{label:"Mouvement",value:"Quartz"},{label:"Finition",value:"PVD Or Rose"},{label:"Verre",value:"Minéral"},{label:"Étanchéité",value:"50M"}],history:"Réinterprétation des codes esthétiques des années 50 avec des matériaux modernes.",price:"219 €",notes:"Index appliqués.",bibliography:[{label:"Lip Himalaya",url:"https://www.lip.fr"}]},
{brand:"Lip",id:"lip-henriette-classique-18mm-2025",name:"Henriette Classique 18 mm",year:2025,img:"liens-photos/lip-pic/henriette_classique_18mm_2025.avif",description:"Montre-bijou ultra-féminine inspirée des archives vintage de la maison.",specs:[{label:"Mouvement",value:"Quartz"},{label:"Diamètre",value:"18 mm"},{label:"Bracelet",value:"Maille milanaise"},{label:"Style",value:"Vintage"}],history:"Nommée en hommage à la tradition familiale des Lip.",price:"169 €",notes:"Boîtier très fin type 'pastille'.",bibliography:[{label:"Lip Archives",url:"https://www.lip.fr"}]},
{brand:"Lip",id:"lip-churchill-femme-2025",name:"Churchill Femme (Variantes 2025)",year:2025,img:"liens-photos/lip-pic/churchill_femme_2025.avif",description:"La montre rectangulaire historique, désormais déclinée dans de nouveaux coloris de cadrans.",specs:[{label:"Forme",value:"Rectangulaire"},{label:"Mouvement",value:"Quartz"},{label:"Calibre",value:"Miyota 5R21"},{label:"Verre",value:"Minéral"}],history:"Modèle T18 offert à Winston Churchill en 1948 par le gouvernement français.",price:"199 €",notes:"Nouveaux cadrans soleillés pour 2025.",bibliography:[{label:"Modèle Churchill",url:"https://www.lip.fr/T18"}]},
{brand:"Lip",id:"lip-mach-2000-femme-2025",name:"Mach 2000 Femme (Nouveautés)",year:2025,img:"liens-photos/lip-pic/mach_2000_femme_2025.avif",description:"Icône du design industriel créée par Roger Tallon, adaptée au poignet féminin.",specs:[{label:"Designer",value:"Roger Tallon"},{label:"Boîtier",value:"Acier/Aluminium"},{label:"Forme",value:"Asymétrique"},{label:"Mouvement",value:"Quartz"}],history:"Créée en 1975, elle a révolutionné l'ergonomie horlogère.",price:"179 €",notes:"La couronne 'boule' est l'élément signature du modèle.",bibliography:[{label:"Design Roger Tallon",url:"https://www.lip.fr/mach2000"}]}                    
);
