window.WATCHES.push({
  brand: "Swatch x Omega",
  id: "moonswatch-mission-to-the-moon",
  name: "MoonSwatch – Mission to the Moon",
  year: 2022,
  img: "liens-photos/swatch-pic/moonswatch_bleue_pic.avif",

  description: "Une réinterprétation ludique et accessible de la Speedmaster Moonwatch.",

  specs: [
    { label: "Boîtier", value: "Bioceramic 42 mm" },
    { label: "Mouvement", value: "Quartz" },
    { label: "Étanchéité", value: "30 m" },
    { label: "Verre", value: "Acrylique" }
  ],

  history: `
La collection MoonSwatch est née d’une collaboration inattendue entre Swatch et Omega.

L’objectif était simple : rendre hommage à la Speedmaster Moonwatch tout en la rendant accessible à un public beaucoup plus large.

Lancée en 2022, la MoonSwatch a immédiatement créé un phénomène mondial.

La collection se compose de 11 coloris inspirés des astres du système solaire.

Cette collaboration a marqué l’histoire récente de l’horlogerie.
`,

  price: "250 €",

  notes: `
Toutes les informations proviennent de sources fiables : communiqués Swatch Group, fiches techniques Omega, et analyses horlogères publiées entre 2022 et 2024.
`,

  bibliography: [
    { label: "Site officiel Omega", url: "https://www.omegawatches.com" },
    { label: "Site officiel Swatch", url: "https://www.swatch.com" },
    { label: "Analyse MoonSwatch – Hodinkee", url: "https://www.hodinkee.com/articles/moonswatch" }
  ],

  bibliography_note: "La bibliographie complète est disponible dans le PDF téléchargeable en bas de page."
},
{
  brand: "Swatch",
  id: "swatch-chasing-peaks-2025",
  name: "Chasing Peaks",
  year: 2025,
  img: "liens-photos/swatch-pic/swatch_chasing_peaks.png",
  description: "Une montre sportive et colorée pensée pour l’aventure, inspirée des activités outdoor et de l’esprit montagne.",
  specs: [
    { label: "Boîtier", value: "Bioceramic 41 mm" },
    { label: "Mouvement", value: "Quartz" },
    { label: "Étanchéité", value: "30 m" },
    { label: "Verre", value: "Plastique renforcé" }
  ],
  history: `
La Swatch Chasing Peaks fait partie des nouveautés 2025 de la marque suisse.
Elle s’inscrit dans la lignée des montres sportives et légères de Swatch, pensées pour accompagner les activités outdoor : randonnée, trail, exploration.
Avec son design coloré et son boîtier en biocéramique, elle reprend les codes modernes de Swatch tout en mettant l’accent sur la robustesse et la légèreté.
Cette montre vise un public jeune, actif et amateur d’aventure, fidèle à l’esprit fun et accessible de la marque.
`,
  price: "100 €",
  notes: `
Les informations proviennent des communiqués Swatch 2025, des fiches techniques officielles et des présentations presse publiées début 2025.
`,
  bibliography: [
    { label: "Site officiel Swatch", url: "https://www.swatch.com" },
    { label: "Communiqué nouveautés Swatch 2025", url: "https://www.swatch.com/fr-fr/news" }
  ],
  bibliography_note: "La bibliographie complète est disponible dans le PDF téléchargeable en bas de page."
},
{brand:"Swatch",id:"swatch-riding-the-clouds-2025",name:"Riding the Clouds",year:2025,img:"liens-photos/swatch-pic/riding_the_clouds.png",description:"Une montre légère inspirée du ciel, mêlant couleurs douces et design dynamique.",specs:[{label:"Boîtier",value:"Bioceramic 41 mm"},{label:"Mouvement",value:"Quartz"},{label:"Étanchéité",value:"30 m"},{label:"Verre",value:"Plastique renforcé"}],history:`Modèle Swatch 2025 inspiré des éléments aériens, pensé pour un public jeune et créatif. Légère, colorée et robuste, fidèle à l’esprit fun de la marque.`,price:"100 €",notes:`Infos issues des communiqués Swatch 2025.`,bibliography:[{label:"Site officiel Swatch",url:"https://www.swatch.com"}]},
{brand:"Swatch",id:"swatch-pollocks-alchemy-2025",name:"Pollock's Alchemy",year:2025,img:"liens-photos/swatch-pic/pollocks_alchemy_2025.png",description:"Une création artistique inspirée de l’univers abstrait de Jackson Pollock.",specs:[{label:"Boîtier",value:"Bioceramic 41 mm"},{label:"Mouvement",value:"Quartz"},{label:"Étanchéité",value:"30 m"},{label:"Verre",value:"Plastique renforcé"}],history:`Modèle issu de la collection Swatch Art 2025, rendant hommage au style gestuel et vibrant de Pollock. Une montre expressive et colorée pensée pour les amateurs d’art moderne.`,price:"100 €",notes:`Infos issues des communiqués Swatch 2025.`,bibliography:[{label:"Site officiel Swatch",url:"https://www.swatch.com"}]},
{brand:"Swatch",id:"swatch-degas-dancers-2025",name:"Degas's Dancers",year:2025,img:"liens-photos/swatch-pic/degas_dancers_2025.png",description:"Une montre inspirée des danseuses emblématiques d’Edgar Degas.",specs:[{label:"Boîtier",value:"Bioceramic 41 mm"},{label:"Mouvement",value:"Quartz"},{label:"Étanchéité",value:"30 m"},{label:"Verre",value:"Plastique renforcé"}],history:`Faisant partie de la collection Art 2025, ce modèle reprend les teintes douces et les mouvements gracieux des œuvres de Degas. Une montre élégante et artistique.`,price:"100 €",notes:`Infos issues des communiqués Swatch 2025.`,bibliography:[{label:"Site officiel Swatch",url:"https://www.swatch.com"}]},
{brand:"Swatch",id:"swatch-klee-bavarian-don-giovanni-2025",name:"Klee's Bavarian Don Giovanni",year:2025,img:"liens-photos/swatch-pic/klee_bavarian_don_giovanni_2025.png",description:"Une montre inspirée des compositions géométriques et colorées de Paul Klee.",specs:[{label:"Boîtier",value:"Bioceramic 41 mm"},{label:"Mouvement",value:"Quartz"},{label:"Étanchéité",value:"30 m"},{label:"Verre",value:"Plastique renforcé"}],history:`Ce modèle rend hommage à l’univers graphique et musical de Paul Klee, combinant formes abstraites et palette vive. Une pièce artistique forte.`,price:"100 €",notes:`Infos issues des communiqués Swatch 2025.`,bibliography:[{label:"Site officiel Swatch",url:"https://www.swatch.com"}]},
{brand:"Swatch",id:"swatch-monets-palazzo-ducale-2025",name:"Monet's Palazzo Ducale",year:2025,img:"liens-photos/swatch-pic/monets_palazzo_ducale_2025.png",description:"Une montre inspirée des couleurs lumineuses de Monet et de son œuvre sur le Palais des Doges.",specs:[{label:"Boîtier",value:"Bioceramic 41 mm"},{label:"Mouvement",value:"Quartz"},{label:"Étanchéité",value:"30 m"},{label:"Verre",value:"Plastique renforcé"}],history:`Issue de la collection Art 2025, cette montre reprend les teintes impressionnistes et la douceur picturale de Monet.`,price:"100 €",notes:`Infos issues des communiqués Swatch 2025.`,bibliography:[{label:"Site officiel Swatch",url:"https://www.swatch.com"}]},
{brand:"Swatch",id:"swatch-monets-palazzo-ducale-pay-2025",name:"Monet's Palazzo Ducale PAY!",year:2025,img:"liens-photos/swatch-pic/monets_palazzo_ducale_pay_2025.png",description:"Version SwatchPAY! de la montre inspirée du Palazzo Ducale de Monet.",specs:[{label:"Boîtier",value:"Bioceramic 41 mm"},{label:"Mouvement",value:"Quartz SwatchPAY!"},{label:"Étanchéité",value:"30 m"},{label:"Verre",value:"Plastique renforcé"}],history:`Variante équipée de la technologie SwatchPAY!, permettant les paiements sans contact tout en conservant le design impressionniste inspiré de Monet.`,price:"120 €",notes:`Infos issues des communiqués Swatch 2025.`,bibliography:[{label:"Site officiel Swatch",url:"https://www.swatch.com"}]},
{brand:"Swatch",id:"swatch-midday-camo-2025",name:"Midday Camo",year:2025,img:"liens-photos/swatch-pic/midday_camo_2025.avif",description:"Montre camouflage aux tons lumineux, typique du style fun et coloré de Swatch.",specs:[{label:"Boîtier",value:"Bioceramic 41 mm"},{label:"Mouvement",value:"Quartz"},{label:"Étanchéité",value:"30 m"},{label:"Verre",value:"Plastique renforcé"}],history:`Modèle 2025 inspiré des motifs camouflage revisités dans une palette vive et moderne.`,price:"100 €",notes:`Infos issues des communiqués Swatch 2025.`,bibliography:[{label:"Site officiel Swatch",url:"https://www.swatch.com"}]},
{brand:"Swatch",id:"swatch-midday-camo-pay-2025",name:"Midday Camo PAY!",year:2025,img:"liens-photos/swatch-pic/midday_camo_pay_2025.avif",description:"Version SwatchPAY! de la Midday Camo, intégrant le paiement sans contact.",specs:[{label:"Boîtier",value:"Bioceramic 41 mm"},{label:"Mouvement",value:"Quartz SwatchPAY!"},{label:"Étanchéité",value:"30 m"},{label:"Verre",value:"Plastique renforcé"}],history:`Variante 2025 équipée de la technologie SwatchPAY!, conservant le design camouflage lumineux.`,price:"120 €",notes:`Infos issues des communiqués Swatch 2025.`,bibliography:[{label:"Site officiel Swatch",url:"https://www.swatch.com"}]},
{brand:"Swatch",id:"swatch-crimson-foliage-2025",name:"Crimson Foliage",year:2025,img:"liens-photos/swatch-pic/crimson_foliage_2025.avif",description:"Montre aux teintes rouges inspirée des feuillages d’automne stylisés.",specs:[{label:"Boîtier",value:"Bioceramic 41 mm"},{label:"Mouvement",value:"Quartz"},{label:"Étanchéité",value:"30 m"},{label:"Verre",value:"Plastique renforcé"}],history:`Modèle 2025 jouant sur une palette rouge profonde évoquant les paysages automnaux.`,price:"100 €",notes:`Infos issues des communiqués Swatch 2025.`,bibliography:[{label:"Site officiel Swatch",url:"https://www.swatch.com"}]},
{brand:"Swatch",id:"swatch-love-and-blah-2025",name:"Love & Blah",year:2025,img:"liens-photos/swatch-pic/love_and_blah_2025.avif",description:"Montre expressive mêlant motifs pop et messages graphiques autour du thème de l’amour.",specs:[{label:"Boîtier",value:"Bioceramic 41 mm"},{label:"Mouvement",value:"Quartz"},{label:"Étanchéité",value:"30 m"},{label:"Verre",value:"Plastique renforcé"}],history:`Modèle 2025 au style pop-art, jouant sur l’humour et les contrastes graphiques.`,price:"100 €",notes:`Infos issues des communiqués Swatch 2025.`,bibliography:[{label:"Site officiel Swatch",url:"https://www.swatch.com"}]},
{brand:"Swatch",id:"swatch-love-in-scarlet-2025",name:"Love in Scarlet",year:2025,img:"liens-photos/swatch-pic/love_in_scarlet_2025.avif",description:"Montre romantique aux tons rouges intenses, inspirée du thème de la passion.",specs:[{label:"Boîtier",value:"Bioceramic 41 mm"},{label:"Mouvement",value:"Quartz"},{label:"Étanchéité",value:"30 m"},{label:"Verre",value:"Plastique renforcé"}],history:`Modèle 2025 jouant sur une esthétique rouge passion, typique des collections thématiques Swatch.`,price:"100 €",notes:`Infos issues des communiqués Swatch 2025.`,bibliography:[{label:"Site officiel Swatch",url:"https://www.swatch.com"}]}, 
{brand:"Swatch",id:"swatch-wavelengths-of-water-2025",name:"WAVELENGTHS OF WATER",year:2025,img:"liens-photos/swatch-pic/wavelengths_of_water_2025.avif",description:"Modèle inspiré par les nuances azurées et les mouvements fluides de l'océan.",specs:[{label:"Mouvement",value:"Quartz"},{label:"Boîtier",value:"Matériau biosourcé"},{label:"Diamètre",value:"41 mm"},{label:"Étanchéité",value:"3 bar"}],history:"Lancée en 2025 au sein de la collection Wavelengths explorant les textures de la nature.",price:"85 €",notes:"Design minimaliste avec cadran dégradé.",bibliography:[{label:"Swatch Official",url:"https://www.swatch.com"}]},
{brand:"Swatch",id:"swatch-wavelengths-of-water-pay-2025",name:"WAVELENGTHS OF WATER PAY!",year:2025,img:"liens-photos/swatch-pic/wavelengths_of_water_pay_2025.avif",description:"Version connectée du modèle Water intégrant la technologie de paiement sans contact NFC.",specs:[{label:"Mouvement",value:"Quartz"},{label:"Technologie",value:"SwatchPAY!"},{label:"Boîtier",value:"Matériau biosourcé"},{label:"Diamètre",value:"41 mm"}],history:"Extension de la gamme fonctionnelle SwatchPAY! pour l'année 2025.",price:"105 €",notes:"Permet le paiement sécurisé via puce intégrée.",bibliography:[{label:"SwatchPAY!",url:"https://www.swatch.com/swatch-pay"}]},
{brand:"Swatch",id:"swatch-wavelengths-of-coral-2025",name:"WAVELENGTHS OF CORAL",year:2025,img:"liens-photos/swatch-pic/wavelengths_of_coral_2025.avif",description:"Garde-temps arborant des tons corail vifs, évoquant la biodiversité marine.",specs:[{label:"Mouvement",value:"Quartz"},{label:"Boîtier",value:"Matériau biosourcé"},{label:"Bracelet",value:"Silicone"},{label:"Étanchéité",value:"3 bar"}],history:"Partie intégrante de la série environnementale Wavelengths de 2025.",price:"85 €",notes:"Utilisation de pigments organiques pour le rendu des couleurs.",bibliography:[{label:"Swatch Collections",url:"https://www.swatch.com"}]},
{brand:"Swatch",id:"swatch-wavelengths-of-sand-2025",name:"WAVELENGTHS OF SAND",year:2025,img:"liens-photos/swatch-pic/wavelengths_of_sand_2025.avif",description:"Design épuré aux tons neutres et beiges rappelant les étendues désertiques et côtières.",specs:[{label:"Mouvement",value:"Quartz"},{label:"Boîtier",value:"Matériau biosourcé"},{label:"Diamètre",value:"34 mm"},{label:"Étanchéité",value:"3 bar"}],history:"Modèle polyvalent de la collection 2025 privilégiant la douceur chromatique.",price:"80 €",notes:"Boîtier format Gent standard.",bibliography:[{label:"Swatch Catalogue",url:"https://www.swatch.com"}]},                    
{brand:"Swatch",id:"swatch-wavelengths-of-moss-2025",name:"WAVELENGTHS OF MOSS",year:2025,img:"liens-photos/swatch-pic/wavelengths_of_moss_2025.avif",description:"Esthétique forestière profonde utilisant des nuances de vert mousse et des textures mates.",specs:[{label:"Mouvement",value:"Quartz"},{label:"Boîtier",value:"Matériau biosourcé"},{label:"Diamètre",value:"41 mm"},{label:"Étanchéité",value:"3 bar"}],history:"Représente l'élément terre dans la collection thématique 2025.",price:"85 €",notes:"Finition soft-touch sur le bracelet.",bibliography:[{label:"Swatch News",url:"https://www.swatch.com"}]},                    
{brand:"Swatch",id:"swatch-prototype-original-1981",name:"Prototype Original",year:1981,img:"liens-photos/swatch-pic/prototype_original_1981.avif",description:"Rare prototype de pré-développement testant la fusion du boîtier et du mouvement pour réduire les coûts.",specs:[{label:"Mouvement",value:"Quartz simplifié"},{label:"Boîtier",value:"Plastique Monobloc"},{label:"Étanchéité",value:"30m"}],history:"Conçu par Elmar Mock et Jacques Müller sous la direction d'Ernst Thomke.",price:"Estimation collection : 5000€+",notes:"Pièce historique non commercialisée à grande échelle.",bibliography:[{label:"Swatch Group History",url:"https://www.swatchgroup.com"}]},
{brand:"Swatch",id:"swatch-gb101-1983",name:"GB101 Black Magic",year:1983,img:"liens-photos/swatch-pic/gb101_1983.avif",description:"L'un des 12 modèles du lancement officiel de 1983, icône du design minimaliste noir.",specs:[{label:"Mouvement",value:"Quartz ETA"},{label:"Diamètre",value:"34mm"},{label:"Matériau",value:"Plastique"}],history:"Fait partie de la collection inaugurale lancée à Zurich le 1er mars 1983.",price:"80€ (neuf) / 300€+ (vintage)",notes:"Le modèle qui a sauvé l'industrie horlogère suisse.",bibliography:[{label:"Swatch Archives",url:"https://www.swatch.com"}]},
{brand:"Swatch",id:"swatch-limelight-1985",name:"Limelight LB103",year:1985,img:"liens-photos/swatch-pic/limelight_1985.avif",description:"Premier modèle 'Luxury' utilisant des cristaux et un design plus sophistiqué pour le marché du soir.",specs:[{label:"Mouvement",value:"Quartz"},{label:"Décoration",value:"Cristaux synthétiques"},{label:"Collection",value:"Lady"}],history:"Marque le début de la segmentation 'chic' de Swatch.",price:"150€",notes:"Boîtier plus petit typique des modèles Lady.",bibliography:[{label:"Vintage Swatch Guide",url:"https://www.swatch.com"}]},
{brand:"Swatch",id:"swatch-breakdance-1985",name:"Breakdance (Special)",year:1985,img:"liens-photos/swatch-pic/breakdance_1985.avif",description:"Édition spéciale célébrant la culture hip-hop, accompagnée d'un protecteur de cadran (Bumper).",specs:[{label:"Mouvement",value:"Quartz"},{label:"Accessoire",value:"Bumper en caoutchouc"},{label:"Design",value:"Keith Haring style inspirations"}],history:"Lancée lors du Swatch World Breakdance Championship à New York.",price:"400€-600€",notes:"Très recherchée avec son packaging original.",bibliography:[{label:"Swatch Art",url:"https://www.swatch.com/art"}]},
{brand:"Swatch",id:"swatch-pop-1986",name:"Pop Swatch",year:1986,img:"liens-photos/swatch-pic/pop_1986.avif",description:"Nouveau concept où la tête de montre est clipsable sur des bracelets larges ou des vêtements.",specs:[{label:"Diamètre",value:"45mm (large)"},{label:"Modularité",value:"Boîtier amovible"},{label:"Style",value:"Oversized"}],history:"Lancement de la gamme POP pour toucher le milieu de la mode.",price:"70€",notes:"Peut se porter en broche ou sur une ceinture.",bibliography:[{label:"Swatch Pop History",url:"https://www.swatch.com"}]},
{brand:"Swatch",id:"swatch-jelly-fish-1987",name:"Jelly Fish (Transparent)",year:1987,img:"liens-photos/swatch-pic/jelly_fish_1987.avif",description:"Premier modèle squelette transparent produit en grande série, révélant les composants internes.",specs:[{label:"Type",value:"Gent Squelette"},{label:"Matériau",value:"Plastique transparent"},{label:"Mouvement",value:"Quartz visible"}],history:"Réédition du modèle de 1983 mais avec une diffusion mondiale massive.",price:"250€ (état neuf)",notes:"Le design le plus emblématique de la marque.",bibliography:[{label:"Swatch Design",url:"https://www.swatch.com"}]},
{brand:"Swatch",id:"swatch-scuba-200-1990",name:"Scuba 200 (Bora Bora)",year:1990,img:"liens-photos/swatch-pic/scuba_200_1990.avif",description:"Première montre de plongée Swatch avec lunette rotative et étanchéité accrue.",specs:[{label:"Étanchéité",value:"200m / 20 Bar"},{label:"Lunette",value:"Unidirectionnelle"},{label:"Diamètre",value:"38mm"}],history:"Succès massif du début des années 90, diversifiant les usages de la Swatch.",price:"90€",notes:"Bien que nommée Scuba 200, elle était surtout portée pour le style.",bibliography:[{label:"Swatch Scuba Collection",url:"https://www.swatch.com"}]},
{brand:"Swatch",id:"swatch-chrono-1990",name:"Chrono (Black Friday)",year:1990,img:"liens-photos/swatch-pic/chrono_1990.avif",description:"Premier chronographe à quartz abordable de la marque avec trois sous-cadrans.",specs:[{label:"Mouvement",value:"Quartz Chronographe"},{label:"Fonctions",value:"60s, 60min, 1/10s"},{label:"Boîtier",value:"37mm"}],history:"Révolution dans le prix des chronographes suisses.",price:"120€",notes:"Modèle précurseur de la collection Chrono qui dominera les années 90.",bibliography:[{label:"Swatch Chrono Manual",url:"https://www.swatch.com"}]},
{brand:"Swatch",id:"swatch-automatic-1991",name:"Automatic (Blue Matic)",year:1991,img:"liens-photos/swatch-pic/automatic_1991.avif",description:"Premier mouvement mécanique à remontage automatique sans pile de la marque.",specs:[{label:"Mouvement",value:"ETA 2840 (Auto)"},{label:"Rubis",value:"21 Jewels"},{label:"Réserve de marche",value:"48h"}],history:"Retour aux sources mécaniques pour Swatch tout en restant abordable.",price:"150€",notes:"Le mouvement est soudé au boîtier et n'est pas réparable.",bibliography:[{label:"ETA Movements",url:"https://www.eta.ch"}]},
{brand:"Swatch",id:"swatch-irony-1994",name:"Irony (Metal)",year:1994,img:"liens-photos/swatch-pic/irony_1994.avif",description:"Lancement de la gamme en acier inoxydable et aluminium, rompant avec le 'tout plastique'.",specs:[{label:"Matériau",value:"Acier inoxydable"},{label:"Poids",value:"Accru par rapport au plastique"},{label:"Cible",value:"Adulte / Professionnel"}],history:"Réponse à la demande des clients pour une montre plus robuste et formelle.",price:"110€",notes:"Marque un tournant majeur dans la perception de la marque.",bibliography:[{label:"Irony Collection",url:"https://www.swatch.com"}]},
{brand:"Swatch",id:"swatch-access-1995",name:"Access (Snowpass)",year:1995,img:"liens-photos/swatch-pic/access_1995.avif",description:"Montre intégrant une puce RFID permettant de servir de forfait de ski mains libres.",specs:[{label:"Technologie",value:"RFID intégré"},{label:"Usage",value:"Forfait de ski / Paiement"},{label:"Mouvement",value:"Quartz"}],history:"Développé en partenariat avec Skidata pour les stations de ski.",price:"85€",notes:"Pionnière des technologies 'contactless' bien avant les smartwatches.",bibliography:[{label:"Swatch Technology",url:"https://www.swatch.com"}]},
{brand:"Swatch",id:"swatch-skin-1997",name:"Skin (Ultra-thin)",year:1997,img:"liens-photos/swatch-pic/skin_1997.avif",description:"Lancement de la ligne de montres la plus fine au monde à l'époque (3.9mm).",specs:[{label:"Épaisseur",value:"3.9 mm"},{label:"Poids",value:"Ultra léger"},{label:"Mouvement",value:"Quartz Slim"}],history:"Inscrite au Guinness World Records pour sa finesse.",price:"95€",notes:"Sensation de ne rien porter au poignet.",bibliography:[{label:"Swatch Skin Collection",url:"https://www.swatch.com"}]},
{brand:"Swatch",id:"swatch-skin-chrono-2002",name:"Skin Chrono",year:2002,img:"liens-photos/swatch-pic/skin_chrono_2002.avif",description:"Le chronographe le plus plat au monde lors de sa sortie, combinant la finesse de la ligne Skin avec une complication chronomètre.",specs:[{label:"Mouvement",value:"Quartz ETA"},{label:"Épaisseur",value:"6.6 mm"},{label:"Boîtier",value:"Plastique"},{label:"Étanchéité",value:"30m"}],history:"Lancée pour prouver que Swatch pouvait miniaturiser une complication chronographe dans un boîtier ultra-fin.",price:"85€",notes:"Modèle très léger, presque imperceptible au poignet.",bibliography:[{label:"Swatch Archives",url:"https://www.swatch.com"}]},                    
{brand:"Swatch",id:"swatch-point-zero-2002",name:".0 (Point Zero)",year:2002,img:"liens-photos/swatch-pic/point_zero_2002.avif",description:"Montre numérique au design radical, précurseur des interfaces minimalistes de la marque au début des années 2000.",specs:[{label:"Mouvement",value:"Quartz Digital"},{label:"Fonctions",value:"Heure, Date"},{label:"Boîtier",value:"Plastique"},{label:"Bracelet",value:"Silicone"}],history:"Fait partie des expérimentations digitales de Swatch pour rajeunir l'image de la gamme plastique.",price:"60€",notes:"Design très typé 'Y2K'.",bibliography:[{label:"Swatch World",url:"https://www.swatch.com"}]},
{brand:"Swatch",id:"swatch-irony-the-chrono-2002",name:"Irony The Chrono",year:2002,img:"liens-photos/swatch-pic/irony_the_chrono_2002.avif",description:"Une version imposante et robuste du chronographe Swatch en acier inoxydable.",specs:[{label:"Mouvement",value:"Quartz ETA"},{label:"Diamètre",value:"47 mm"},{label:"Boîtier",value:"Acier Inoxydable"},{label:"Étanchéité",value:"30m"}],history:"Conçue pour concurrencer les montres sportives de plus grand diamètre alors en vogue.",price:"140€",notes:"L'un des modèles les plus lourds de Swatch à l'époque.",bibliography:[{label:"Catalogue Irony",url:"https://www.swatch.com"}]},                   
{brand:"Swatch",id:"swatch-irony-scuba-200-2003",name:"Irony Scuba 200",year:2003,img:"liens-photos/swatch-pic/irony_scuba_200_2003.avif",description:"Montre de plongée en acier avec lunette rotative et étanchéité renforcée.",specs:[{label:"Mouvement",value:"Quartz ETA"},{label:"Étanchéité",value:"200m"},{label:"Boîtier",value:"Acier"},{label:"Lunette",value:"Unidirectionnelle"}],history:"L'évolution métallique de la célèbre Scuba 200 en plastique des années 90.",price:"95€",notes:"Véritable montre de plongée certifiée ISO.",bibliography:[{label:"Swatch Scuba History",url:"https://www.swatch.com"}]},           
{brand:"Swatch",id:"swatch-diaphane-one-turning-gold-2003",name:"Diaphane One Turning Gold",year:2003,img:"liens-photos/swatch-pic/diaphane_one_turning_gold_2003.avif",description:"Haute horlogerie par Swatch présentant un mouvement squelette qui tourne sur lui-même.",specs:[{label:"Mouvement",value:"Manuel (Carrousel)"},{label:"Matériaux",value:"Or 18k et Plastique"},{label:"Complication",value:"Plate-forme tournante"}],history:"Édition limitée prestigieuse démontrant le savoir-faire technique du Groupe Swatch.",price:"7500€",notes:"Le mouvement effectue deux rotations par heure.",bibliography:[{label:"Swatch Luxury",url:"https://www.swatch.com"}]},                
{brand:"Swatch",id:"swatch-fun-boarder-2003",name:"Fun Boarder",year:2003,img:"liens-photos/swatch-pic/fun_boarder_2003.avif",description:"Montre lifestyle pour les amateurs de sports de glisse avec des fonctions spécifiques.",specs:[{label:"Mouvement",value:"Quartz"},{label:"Diamètre",value:"44 mm"},{label:"Boîtier",value:"Plastique"},{label:"Bracelet",value:"Textile/Scratch"}],history:"Lancée pour accompagner la culture snowboard très forte au début des années 2000.",price:"70€",notes:"Précurseur des modèles avec altimètre.",bibliography:[{label:"Swatch Sport",url:"https://www.swatch.com"}]},                   
{brand:"Swatch",id:"swatch-paparazzi-2004",name:"Paparazzi (MSN Direct)",year:2004,img:"liens-photos/swatch-pic/paparazzi_2004.avif",description:"Une des premières montres connectées recevant des données par ondes radio via le service MSN Direct de Microsoft.",specs:[{label:"Technologie",value:"Puce MSN Direct"},{label:"Affichage",value:"LCD Digital"},{label:"Fonctions",value:"Météo, News, Bourse"}],history:"Fruit d'une collaboration entre Bill Gates et Nicolas Hayek.",price:"150€",notes:"Le service a été arrêté par Microsoft en 2012.",bibliography:[{label:"Wired Magazine",url:"https://www.wired.com"}]},
{brand:"Swatch",id:"swatch-jelly-in-jelly-2004",name:"Jelly in Jelly",year:2004,img:"liens-photos/swatch-pic/jelly_in_jelly_2004.avif",description:"Nouveau concept de construction flexible et transparente, offrant une plus grande fluidité de design.",specs:[{label:"Mouvement",value:"Quartz"},{label:"Boîtier",value:"Plastique injecté"},{label:"Transparence",value:"Totale"}],history:"Ligne créée pour moderniser la structure de la Gent classique.",price:"55€",notes:"Très populaire pour ses éditions limitées artistiques.",bibliography:[{label:"Swatch Design",url:"https://www.swatch.com"}]},
{brand:"Swatch",id:"swatch-fun-boarder-altimetre-2005",name:"Fun Boarder Altimètre",year:2005,img:"liens-photos/swatch-pic/fun_boarder_2005.avif",description:"Évolution de la Fun Boarder intégrant un capteur de pression pour mesurer l'altitude.",specs:[{label:"Mouvement",value:"Quartz"},{label:"Capteur",value:"Altimètre électronique"},{label:"Usage",value:"Ski / Snowboard"}],history:"Utilisée par les skieurs pour suivre leur dénivelé sur les pistes.",price:"85€",notes:"Le réglage se fait par la couronne et la lunette.",bibliography:[{label:"Swatch Tech",url:"https://www.swatch.com"}]},
{brand:"Swatch",id:"swatch-fun-scuba-morays-bite-2006",name:"Fun Scuba Moray's Bite",year:2006,img:"liens-photos/swatch-pic/fun_scuba_2006.avif",description:"Montre de plongée avec profondimètre automatique s'activant une fois immergée.",specs:[{label:"Mouvement",value:"Quartz"},{label:"Fonction",value:"Profondimètre (max 40m)"},{label:"Boîtier",value:"Plastique 47mm"}],history:"Succès majeur grâce à son prix accessible pour un profondimètre.",price:"75€",notes:"L'aiguille des heures indique la profondeur, celle des minutes le temps de plongée.",bibliography:[{label:"Diving Watch Guide",url:"https://www.swatch.com"}]},
{brand:"Swatch",id:"swatch-irony-nabab-2006",name:"Irony Nabab",year:2006,img:"liens-photos/swatch-pic/irony_nabab_2006.avif",description:"Série haut de gamme de la ligne Irony caractérisée par des boîtiers très larges et des bracelets en cuir épais.",specs:[{label:"Boîtier",value:"Acier Poli"},{label:"Mouvement",value:"Quartz ETA"},{label:"Design",value:"Oversized"}],history:"Ciblait un marché plus urbain et 'fashion' que les modèles sportifs.",price:"160€",notes:"Une des Swatch les plus imposantes de l'époque.",bibliography:[{label:"Swatch Fashion",url:"https://www.swatch.com"}]},
{brand:"Swatch",id:"swatch-irony-chrono-retrograde-2007",name:"Irony Chrono Retrograde",year:2007,img:"liens-photos/swatch-pic/irony_chrono_retrograde_2007.avif",description:"Chronographe avec aiguilles rétrogrades qui reviennent à zéro instantanément après avoir parcouru leur segment.",specs:[{label:"Mouvement",value:"Quartz ETA G15.261"},{label:"Fonctions",value:"Chronographe 30 min"},{label:"Boîtier",value:"Acier Inoxydable"}],history:"Démocratisation d'une complication souvent réservée à la haute horlogerie.",price:"180€",notes:"L'animation des aiguilles au reset est spectaculaire.",bibliography:[{label:"ETA Movements",url:"https://www.eta.ch"}]},
{brand:"Swatch",id:"swatch-007-villain-2008",name:"007 Villain Collection",year:2008,img:"liens-photos/swatch-pic/007_villain_2008.avif",description:"Collection dédiée aux ennemis emblématiques de James Bond.",specs:[{label:"Série",value:"22 modèles"},{label:"Mouvements",value:"Variés (Quartz/Auto)"},{label:"Thème",value:"Cinéma / James Bond"}],history:"Célèbre le 46ème anniversaire de 007 au cinéma.",price:"Varié",notes:"Chaque montre représente un méchant spécifique (ex: Goldfinger, Jaws).",bibliography:[{label:"Bond Lifestyle",url:"https://www.jamesbondlifestyle.com"}]},
{brand:"Swatch",id:"swatch-chrono-automatic-2009",name:"Chrono Automatic",year:2009,img:"liens-photos/swatch-pic/chrono_automatic_2009.avif",description:"Premier chronographe automatique abordable utilisant le nouveau mouvement ETA C01.211.",specs:[{label:"Mouvement",value:"Automatique C01.211"},{label:"Réserve de marche",value:"45 heures"},{label:"Boîtier",value:"Plastique/Fond transparent"}],history:"Révolutionnaire pour son prix défiant toute concurrence sur le segment automatique.",price:"285€",notes:"Mouvement basé sur le célèbre Lemania 5100.",bibliography:[{label:"Le Point Horlogerie",url:"https://www.lepoint.fr"}]},
{brand:"Swatch",id:"swatch-new-gent-2010",name:"New Gent",year:2010,img:"liens-photos/swatch-pic/new_gent_2010.avif",description:"Mise à jour de la Gent classique avec un diamètre porté à 41mm pour s'adapter aux standards modernes.",specs:[{label:"Diamètre",value:"41 mm"},{label:"Mouvement",value:"Quartz"},{label:"Boîtier",value:"Plastique"},{label:"Étanchéité",value:"30m"}],history:"Réponse de Swatch au déclin des petits diamètres de 34mm.",price:"65€",notes:"Devenue le nouveau standard de la marque.",bibliography:[{label:"Swatch Collection",url:"https://www.swatch.com"}]},
{brand:"Swatch",id:"swatch-touch-2011",name:"Touch",year:2011,img:"liens-photos/swatch-pic/touch_2011.avif",description:"Montre entièrement numérique sans boutons, contrôlée par un écran tactile incurvé.",specs:[{label:"Affichage",value:"LCD Tactile"},{label:"Fonctions",value:"2 fuseaux, Chrono, Alarme"},{label:"Bracelet",value:"Silicone"}],history:"Inspirée par l'essor des smartphones et des interfaces tactiles.",price:"110€",notes:"Permet de défiler entre les fonctions par simple balayage.",bibliography:[{label:"TechCrunch",url:"https://techcrunch.com"}]},
{brand:"Swatch",id:"swatch-sistem51-2013",name:"Sistem51",year:2013,img:"liens-photos/swatch-pic/sistem51_2013.avif",description:"Premier mouvement automatique assemblé entièrement par des robots, composé de seulement 51 pièces.",specs:[{label:"Mouvement",value:"Automatique (51 pièces)"},{label:"Réserve de marche",value:"90 heures"},{label:"Précision",value:"+/- 10s par jour"}],history:"Présentée à Baselworld 2013 comme une prouesse industrielle.",price:"150€",notes:"Le mouvement est maintenu par une seule vis centrale.",bibliography:[{label:"Hodinkee",url:"https://www.hodinkee.com"}]},
{brand:"Swatch",id:"swatch-bellamy-2015",name:"Bellamy",year:2015,img:"liens-photos/swatch-pic/bellamy_2015.avif",description:"Première Swatch intégrant une puce NFC pour le paiement sans contact.",specs:[{label:"Mouvement",value:"Quartz"},{label:"Technologie",value:"NFC (Visa/Mastercard)"},{label:"Autonomie",value:"Pile classique (2 ans)"}],history:"Lancée d'abord en Chine puis en Suisse pour contrer l'Apple Watch.",price:"90€",notes:"Le paiement fonctionne même si la pile de la montre est vide.",bibliography:[{label:"NFC World",url:"https://www.nfcw.com"}]},
{brand:"Swatch",id:"swatch-sistem51-irony-2016",name:"Sistem51 Irony",year:2016,img:"liens-photos/swatch-pic/sistem51_irony_2016.avif",description:"Adaptation du mouvement révolutionnaire Sistem51 dans un boîtier en acier inoxydable.",specs:[{label:"Mouvement",value:"Automatique 51 pièces"},{label:"Boîtier",value:"Acier 316L"},{label:"Fond",value:"Transparent"}],history:"Réponse aux clients souhaitant une montre automatique Swatch plus formelle.",price:"195€",notes:"Marque le passage de la Sistem51 vers un segment plus premium.",bibliography:[{label:"Montres de Luxe",url:"https://www.montres-de-luxe.com"}]},
{brand:"Swatch",id:"swatch-skin-irony-2018",name:"Skin Irony",year:2018,img:"liens-photos/swatch-pic/skin_irony_2018.avif",description:"La fusion entre la finesse extrême de la Skin et la robustesse de l'acier Irony.",specs:[{label:"Épaisseur",value:"5.8 mm"},{label:"Boîtier",value:"Acier Inoxydable"},{label:"Mouvement",value:"Quartz ETA"}],history:"Considérée comme la Swatch la plus élégante pour les tenues de bureau.",price:"145€",notes:"Profil ultra-bas parfait sous une chemise.",bibliography:[{label:"Swatch Press",url:"https://www.swatch.com"}]},
{brand:"Swatch",id:"swatch-flymagic-2019",name:"Flymagic",year:2019,img:"liens-photos/swatch-pic/flymagic_2019.avif",description:"Édition limitée présentant un mouvement Sistem51 inversé et le nouveau spiral Nivachron antimagnétique.",specs:[{label:"Mouvement",value:"Automatique Inversé"},{label:"Spiral",value:"Nivachron (Titane)"},{label:"Limitation",value:"500 pièces par modèle"}],history:"Lancement technologique majeur pour contrer les champs magnétiques du quotidien.",price:"1500€",notes:"La masse oscillante est située côté cadran.",bibliography:[{label:"Monochrome Watches",url:"https://monochrome-watches.com"}]},
{brand:"Swatch",id:"swatch-big-bold-bioceramic-2021",name:"Big Bold Bioceramic",year:2021,img:"liens-photos/swatch-pic/big_bold_bioceramic_2021.avif",description:"Introduction d'un nouveau matériau composite composé de 2/3 de céramique et 1/3 de plastique biosourcé.",specs:[{label:"Matériau",value:"Biocéramique"},{label:"Diamètre",value:"47 mm"},{label:"Toucher",value:"Velouté / Soyeux"}],history:"Étape clé vers la durabilité écologique pour Swatch.",price:"125€",notes:"Matériau plus résistant et plus léger que la céramique traditionnelle.",bibliography:[{label:"Journal Haute Horlogerie",url:"https://www.hautehorlogerie.org"}]},
{brand:"Swatch",id:"swatch-blancpain-scuba-2023",name:"Scuba Fifty Fathoms",year:2023,img:"liens-photos/swatch-pic/scuba_fifty_fathoms_2023.avif",description:"Hommage à la première montre de plongée moderne, équipée du mouvement Sistem51.",specs:[{label:"Mouvement",value:"Automatique Sistem51"},{label:"Étanchéité",value:"91m (50 fathoms)"},{label:"Matériau",value:"Biocéramique"}],history:"Célèbre les 70 ans de la Fifty Fathoms originale.",price:"390€",notes:"Étanche en eau profonde, sans pile.",bibliography:[{label:"Blancpain Official",url:"https://www.blancpain.com"}]},
{brand:"Swatch",id:"swatch-what-if-2023",name:"What If?",year:2023,img:"liens-photos/swatch-pic/what_if_2023.avif",description:"Design explorant un prototype carré que Swatch aurait pu choisir à la place du rond en 1982.",specs:[{label:"Forme",value:"Carrée (33x33mm)"},{label:"Matériau",value:"Biocéramique"},{label:"Verre",value:"Source biosourcée bord à bord"}],history:"Collection célébrant les 40 ans de la marque en revisitant son histoire alternative.",price:"105€",notes:"Le fond de pile affiche le design d'un des premiers cadrans de 1983.",bibliography:[{label:"GQ Magazine",url:"https://www.gq.com"}]},
{brand:"Swatch",id:"swatch-moonswatch-moonphase-2024",name:"MoonSwatch Mission to the Moonphase",year:2024,img:"liens-photos/swatch-pic/moonswatch_moonphase_2024.avif",description:"Première MoonSwatch intégrant une complication phase de lune avec le personnage Snoopy.",specs:[{label:"Complication",value:"Phase de lune"},{label:"Particularité",value:"Encre UV cachée"},{label:"Matériau",value:"Biocéramique"}],history:"Référence au Silver Snoopy Award décerné par la NASA à Omega.",price:"310€",notes:"Existe en versions Full Moon (Blanche) et New Moon (Noire).",bibliography:[{label:"Time and Tide",url:"https://timeandtidewatches.com"}]}
);
