window.WATCHES.push(
{brand:"Yema",id:"yema-navygraf-heritage-2025",name:"Navygraf Heritage",year:2025,img:"liens-photos/yema-pic/navygraf_heritage_2025.avif",description:"Plongeuse rétro inspirée des Navygraf historiques, au style marin authentique.",specs:[{label:"Boîtier",value:"Acier 39 mm"},{label:"Mouvement",value:"Automatique CMM.10"},{label:"Étanchéité",value:"300 m"},{label:"Verre",value:"Saphir"}],history:`Réédition 2025 de la Navygraf, reprenant les codes marins des modèles des années 70 avec un mouvement manufacture moderne.`,price:"990 €",notes:`Infos issues du catalogue Yema 2025.`,bibliography:[{label:"Site officiel Yema",url:"https://yema.com"}]},
{brand:"Yema",id:"yema-superman-tourbillon-cmm31-2025",name:"Superman Tourbillon CMM.31",year:2025,img:"liens-photos/yema-pic/superman_tourbillon_cmm31_2025.avif",description:"Version tourbillon haut de gamme de la Superman, équipée du calibre manufacture CMM.31.",specs:[{label:"Boîtier",value:"Acier 41 mm"},{label:"Mouvement",value:"Tourbillon CMM.31"},{label:"Étanchéité",value:"300 m"},{label:"Verre",value:"Saphir"}],history:`Modèle d’exception 2025 intégrant un tourbillon manufacture, une première dans la gamme Superman.`,price:"8900 €",notes:`Infos issues du catalogue Yema 2025.`,bibliography:[{label:"Site officiel Yema",url:"https://yema.com"}]},
{brand:"Yema",id:"yema-superman-swiss-edition-2025",name:"Superman Swiss Edition",year:2025,img:"liens-photos/yema-pic/superman_swiss_edition_2025.avif",description:"Version Swiss Made de la Superman, dotée d’un mouvement suisse haut de gamme.",specs:[{label:"Boîtier",value:"Acier 41 mm"},{label:"Mouvement",value:"Automatique Sellita SW200"},{label:"Étanchéité",value:"300 m"},{label:"Verre",value:"Saphir"}],history:`Édition 2025 produite en Suisse, combinant le design iconique de la Superman avec une motorisation suisse reconnue.`,price:"1190 €",notes:`Infos issues du catalogue Yema 2025.`,bibliography:[{label:"Site officiel Yema",url:"https://yema.com"}]},
{brand:"Yema",id:"yema-superman-slim-cmm20-2025",name:"Superman Slim CMM.20",year:2025,img:"liens-photos/yema-pic/superman_slim_cmm20_2025.avif",description:"Version affinée de la Superman, équipée du calibre manufacture extra-plat CMM.20.",specs:[{label:"Boîtier",value:"Acier 39 mm"},{label:"Mouvement",value:"Automatique CMM.20"},{label:"Étanchéité",value:"300 m"},{label:"Verre",value:"Saphir"}],history:`La Superman Slim 2025 modernise la plongeuse iconique avec un mouvement manufacture plus fin et un profil plus confortable.`,price:"1290 €",notes:`Infos issues du catalogue Yema 2025.`,bibliography:[{label:"Site officiel Yema",url:"https://yema.com"}]},
{brand:"Yema",id:"yema-superman-500-dato-2025",name:"Superman 500 Dato",year:2025,img:"liens-photos/yema-pic/superman_500_dato_2025.avif",description:"Version dateur de la Superman 500, plongeuse robuste et modernisée.",specs:[{label:"Boîtier",value:"Acier 41 mm"},{label:"Mouvement",value:"Automatique"},{label:"Étanchéité",value:"500 m"},{label:"Verre",value:"Saphir"}],history:`La Superman 500 Dato 2025 renforce les capacités de plongée tout en ajoutant une complication date discrète.`,price:"1190 €",notes:`Infos issues du catalogue Yema 2025.`,bibliography:[{label:"Site officiel Yema",url:"https://yema.com"}]},
{brand:"Yema",id:"yema-superman-500-gmt-2025",name:"Superman 500 GMT",year:2025,img:"liens-photos/yema-pic/superman_500_gmt_2025.avif",description:"Version GMT de la Superman 500, pensée pour les voyageurs et plongeurs.",specs:[{label:"Boîtier",value:"Acier 41 mm"},{label:"Mouvement",value:"Automatique GMT"},{label:"Étanchéité",value:"500 m"},{label:"Verre",value:"Saphir"}],history:`La Superman 500 GMT 2025 combine robustesse extrême et fonction second fuseau horaire.`,price:"1490 €",notes:`Infos issues du catalogue Yema 2025.`,bibliography:[{label:"Site officiel Yema",url:"https://yema.com"}]},
{brand:"Yema",id:"yema-navygraf-mn-cmm10-2025",name:"Navygraf Marine Nationale CMM.10",year:2025,img:"liens-photos/yema-pic/navygraf_mn_cmm10_2025.avif",description:"Montre officielle Marine Nationale équipée du calibre manufacture CMM.10.",specs:[{label:"Boîtier",value:"Acier 39 mm"},{label:"Mouvement",value:"Automatique CMM.10"},{label:"Étanchéité",value:"300 m"},{label:"Verre",value:"Saphir"}],history:`Partenariat officiel avec la Marine Nationale, cette édition 2025 reprend les codes militaires et marins historiques de Yema.`,price:"1090 €",notes:`Infos issues du catalogue Yema 2025.`,bibliography:[{label:"Site officiel Yema",url:"https://yema.com"}]},
{brand:"Yema",id:"yema-navygraf-slim-cmm20-limited-2025",name:"Navygraf Slim CMM.20 – Édition Limitée",year:2025,img:"liens-photos/yema-pic/navygraf_slim_cmm20_limited_2025.avif",description:"Version extra-plate de la Navygraf, équipée du calibre manufacture CMM.20, produite en édition limitée.",specs:[{label:"Boîtier",value:"Acier 38.5 mm"},{label:"Mouvement",value:"Automatique CMM.20"},{label:"Étanchéité",value:"200 m"},{label:"Verre",value:"Saphir"}],history:`Édition limitée 2025 combinant finesse, mouvement manufacture et design marin moderne.`,price:"1390 €",notes:`Infos issues du catalogue Yema 2025.`,bibliography:[{label:"Site officiel Yema",url:"https://yema.com"}]},
{brand:"Yema",id:"yema-navygraf-mn-gmt-2025",name:"Navygraf Marine Nationale GMT",year:2025,img:"liens-photos/yema-pic/navygraf_mn_gmt_2025.avif",description:"Version GMT de la Navygraf Marine Nationale, pensée pour les missions et déplacements internationaux.",specs:[{label:"Boîtier",value:"Acier 39 mm"},{label:"Mouvement",value:"Automatique GMT"},{label:"Étanchéité",value:"300 m"},{label:"Verre",value:"Saphir"}],history:`Modèle 2025 issu du partenariat Marine Nationale, intégrant un second fuseau horaire pour un usage opérationnel.`,price:"1290 €",notes:`Infos issues du catalogue Yema 2025.`,bibliography:[{label:"Site officiel Yema",url:"https://yema.com"}]}
);
